 services:
   api-students:
     build: ./api-students
     ports:
       - 8000:8000
   websimple:
     build: ./websimple
     ports:
       - 8080:80
   webplantillas:
     build: ./webplantillas
     ports:
       - 8081:81
